language: node_js
node_js:
  - "8.4"

before_install:
  - cd ..
  - git clone http://github.com/bostontrader/polo-catbox
  - cd polo-catbox
  - npm install
  - npm test
  - npm start &
  - cd ../polonlyze
  - pwd
